language: php
php:
  - 5.3
  - 5.4

before_script:
  - rm /tmp/oodb.db
  - touch /tmp/oodb.db
  - mysql -e 'create database oodb;'
  - psql -c 'create database oodb;' -U postgres
  - php replica.php
  - cp rb.php testing/cli/testcontainer/rb.php  
  - cd testing/cli
  - php main_nocov.php 
 
script: ./start.sh
